// Code generated by goyacc -o yacc.go yacc.y. DO NOT EDIT.

//line yacc.y:2
package fakescript_go

import __yyfmt__ "fmt"

//line yacc.y:2

//line yacc.y:6
type yySymType struct {
	yys int
	s   string
	sn  syntree_node
}

const VAR_BEGIN = 57346
const RETURN = 57347
const BREAK = 57348
const FUNC = 57349
const WHILE = 57350
const FTRUE = 57351
const FFALSE = 57352
const IF = 57353
const THEN = 57354
const ELSE = 57355
const END = 57356
const STRING_DEFINITION = 57357
const IDENTIFIER = 57358
const NUMBER = 57359
const SINGLE_LINE_COMMENT = 57360
const DIVIDE_MOD = 57361
const ARG_SPLITTER = 57362
const PLUS = 57363
const MINUS = 57364
const DIVIDE = 57365
const MULTIPLY = 57366
const ASSIGN = 57367
const MORE = 57368
const LESS = 57369
const MORE_OR_EQUAL = 57370
const LESS_OR_EQUAL = 57371
const EQUAL = 57372
const NOT_EQUAL = 57373
const OPEN_BRACKET = 57374
const CLOSE_BRACKET = 57375
const AND = 57376
const OR = 57377
const FKFLOAT = 57378
const PLUS_ASSIGN = 57379
const MINUS_ASSIGN = 57380
const DIVIDE_ASSIGN = 57381
const MULTIPLY_ASSIGN = 57382
const DIVIDE_MOD_ASSIGN = 57383
const COLON = 57384
const FOR = 57385
const INC = 57386
const FAKE = 57387
const FKUUID = 57388
const OPEN_SQUARE_BRACKET = 57389
const CLOSE_SQUARE_BRACKET = 57390
const FCONST = 57391
const PACKAGE = 57392
const INCLUDE = 57393
const IDENTIFIER_DOT = 57394
const IDENTIFIER_POINTER = 57395
const STRUCT = 57396
const IS = 57397
const NOT = 57398
const CONTINUE = 57399
const YIELD = 57400
const SLEEP = 57401
const SWITCH = 57402
const CASE = 57403
const DEFAULT = 57404
const NEW_ASSIGN = 57405
const ELSEIF = 57406
const RIGHT_POINTER = 57407
const STRING_CAT = 57408
const OPEN_BIG_BRACKET = 57409
const CLOSE_BIG_BRACKET = 57410
const FNULL = 57411

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"VAR_BEGIN",
	"RETURN",
	"BREAK",
	"FUNC",
	"WHILE",
	"FTRUE",
	"FFALSE",
	"IF",
	"THEN",
	"ELSE",
	"END",
	"STRING_DEFINITION",
	"IDENTIFIER",
	"NUMBER",
	"SINGLE_LINE_COMMENT",
	"DIVIDE_MOD",
	"ARG_SPLITTER",
	"PLUS",
	"MINUS",
	"DIVIDE",
	"MULTIPLY",
	"ASSIGN",
	"MORE",
	"LESS",
	"MORE_OR_EQUAL",
	"LESS_OR_EQUAL",
	"EQUAL",
	"NOT_EQUAL",
	"OPEN_BRACKET",
	"CLOSE_BRACKET",
	"AND",
	"OR",
	"FKFLOAT",
	"PLUS_ASSIGN",
	"MINUS_ASSIGN",
	"DIVIDE_ASSIGN",
	"MULTIPLY_ASSIGN",
	"DIVIDE_MOD_ASSIGN",
	"COLON",
	"FOR",
	"INC",
	"FAKE",
	"FKUUID",
	"OPEN_SQUARE_BRACKET",
	"CLOSE_SQUARE_BRACKET",
	"FCONST",
	"PACKAGE",
	"INCLUDE",
	"IDENTIFIER_DOT",
	"IDENTIFIER_POINTER",
	"STRUCT",
	"IS",
	"NOT",
	"CONTINUE",
	"YIELD",
	"SLEEP",
	"SWITCH",
	"CASE",
	"DEFAULT",
	"NEW_ASSIGN",
	"ELSEIF",
	"RIGHT_POINTER",
	"STRING_CAT",
	"OPEN_BIG_BRACKET",
	"CLOSE_BIG_BRACKET",
	"FNULL",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacc.y:1446

func init() {
	yyErrorVerbose = true // set the global that enables showing full errors
}

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 83,
	19, 132,
	21, 132,
	22, 132,
	23, 132,
	24, 132,
	66, 132,
	-2, 121,
	-1, 84,
	19, 130,
	21, 130,
	22, 130,
	23, 130,
	24, 130,
	66, 130,
	-2, 122,
	-1, 85,
	20, 115,
	25, 115,
	63, 115,
	-2, 133,
	-1, 104,
	12, 85,
	20, 85,
	33, 85,
	34, 85,
	35, 85,
	-2, 134,
	-1, 105,
	12, 86,
	20, 86,
	33, 86,
	34, 86,
	35, 86,
	-2, 135,
	-1, 108,
	19, 131,
	21, 131,
	22, 131,
	23, 131,
	24, 131,
	66, 131,
	-2, 89,
	-1, 109,
	19, 133,
	21, 133,
	22, 133,
	23, 133,
	24, 133,
	66, 133,
	-2, 90,
	-1, 114,
	19, 131,
	21, 131,
	22, 131,
	23, 131,
	24, 131,
	66, 131,
	-2, 96,
	-1, 115,
	19, 133,
	21, 133,
	22, 133,
	23, 133,
	24, 133,
	66, 133,
	-2, 97,
	-1, 123,
	26, 122,
	27, 122,
	28, 122,
	29, 122,
	30, 122,
	31, 122,
	-2, 130,
	-1, 170,
	19, 131,
	21, 131,
	22, 131,
	23, 131,
	24, 131,
	66, 131,
	-2, 105,
	-1, 171,
	19, 133,
	21, 133,
	22, 133,
	23, 133,
	24, 133,
	66, 133,
	-2, 106,
	-1, 229,
	19, 131,
	21, 131,
	22, 131,
	23, 131,
	24, 131,
	65, 60,
	66, 131,
	-2, 105,
	-1, 230,
	19, 133,
	21, 133,
	22, 133,
	23, 133,
	24, 133,
	65, 61,
	66, 133,
	-2, 106,
}

const yyPrivate = 57344

const yyLast = 1339

var yyAct = [...]int16{
	85, 220, 228, 239, 219, 183, 195, 113, 169, 152,
	59, 153, 78, 151, 150, 152, 241, 148, 149, 151,
	150, 101, 33, 34, 247, 193, 121, 182, 37, 92,
	35, 119, 117, 196, 33, 34, 196, 231, 92, 6,
	37, 17, 35, 7, 235, 142, 12, 3, 152, 38,
	148, 149, 151, 150, 43, 6, 153, 146, 12, 36,
	41, 38, 153, 118, 181, 93, 95, 221, 100, 120,
	118, 36, 41, 55, 93, 95, 109, 109, 115, 8,
	40, 22, 39, 124, 57, 145, 127, 125, 137, 109,
	124, 124, 40, 54, 39, 153, 46, 126, 111, 135,
	146, 155, 156, 109, 224, 226, 97, 109, 109, 128,
	129, 130, 131, 132, 127, 224, 133, 256, 171, 171,
	137, 137, 177, 17, 157, 180, 124, 173, 255, 171,
	171, 171, 171, 171, 176, 225, 147, 187, 188, 189,
	190, 191, 53, 124, 31, 100, 124, 124, 124, 124,
	124, 124, 124, 124, 124, 224, 109, 109, 96, 254,
	109, 109, 109, 109, 109, 109, 28, 91, 236, 115,
	246, 134, 266, 198, 168, 200, 222, 209, 210, 178,
	167, 155, 156, 154, 155, 156, 186, 32, 211, 155,
	156, 263, 21, 109, 230, 224, 224, 109, 51, 47,
	49, 232, 155, 156, 47, 155, 156, 56, 234, 223,
	185, 50, 26, 98, 227, 179, 95, 83, 100, 144,
	44, 240, 109, 238, 27, 124, 124, 124, 25, 100,
	243, 29, 23, 30, 108, 108, 114, 18, 13, 207,
	240, 16, 251, 242, 252, 271, 250, 108, 260, 22,
	258, 194, 218, 244, 245, 5, 20, 48, 45, 100,
	10, 108, 11, 79, 100, 108, 108, 260, 100, 269,
	67, 112, 15, 100, 74, 100, 170, 170, 100, 73,
	72, 71, 70, 100, 69, 68, 66, 170, 170, 170,
	170, 170, 160, 159, 162, 163, 161, 164, 65, 64,
	63, 62, 84, 61, 60, 136, 42, 141, 141, 103,
	24, 19, 14, 9, 108, 108, 248, 4, 108, 108,
	108, 108, 108, 108, 2, 1, 253, 114, 0, 0,
	0, 257, 94, 0, 0, 262, 0, 174, 175, 264,
	0, 0, 0, 141, 0, 0, 110, 110, 116, 0,
	267, 108, 229, 122, 0, 108, 272, 0, 0, 110,
	141, 0, 0, 141, 141, 141, 141, 141, 141, 141,
	141, 141, 0, 158, 0, 0, 0, 110, 110, 0,
	108, 0, 0, 0, 0, 123, 0, 0, 172, 172,
	0, 0, 140, 140, 0, 0, 0, 0, 138, 172,
	172, 172, 172, 172, 0, 123, 259, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 165, 166, 0, 0,
	0, 0, 139, 143, 0, 259, 110, 110, 140, 0,
	110, 110, 110, 110, 110, 110, 0, 0, 0, 116,
	0, 0, 141, 141, 141, 197, 0, 0, 140, 140,
	140, 140, 140, 140, 140, 140, 140, 0, 184, 0,
	0, 0, 0, 110, 172, 0, 0, 110, 0, 212,
	213, 214, 215, 216, 217, 0, 0, 0, 184, 199,
	184, 201, 202, 203, 204, 205, 206, 0, 0, 0,
	0, 0, 110, 0, 0, 0, 0, 0, 91, 77,
	80, 0, 75, 33, 34, 76, 233, 0, 274, 37,
	92, 35, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 82, 140, 140, 140,
	38, 0, 0, 0, 0, 0, 0, 86, 0, 87,
	36, 41, 0, 0, 0, 0, 93, 95, 0, 0,
	0, 81, 90, 89, 88, 0, 0, 184, 184, 184,
	0, 40, 0, 39, 91, 77, 80, 0, 75, 33,
	34, 76, 0, 0, 273, 37, 92, 35, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 33, 34, 0,
	0, 0, 82, 37, 0, 35, 38, 0, 0, 0,
	0, 0, 0, 86, 0, 87, 36, 41, 0, 0,
	0, 0, 93, 95, 38, 0, 0, 81, 90, 89,
	88, 0, 0, 0, 36, 41, 0, 40, 0, 39,
	91, 77, 80, 0, 75, 33, 34, 76, 0, 0,
	270, 37, 92, 35, 0, 40, 52, 39, 0, 0,
	0, 0, 0, 33, 34, 0, 0, 0, 82, 37,
	0, 35, 38, 0, 0, 0, 0, 0, 0, 86,
	0, 87, 36, 41, 0, 0, 0, 0, 93, 95,
	38, 0, 0, 81, 90, 89, 88, 0, 0, 0,
	36, 41, 0, 40, 0, 39, 91, 77, 80, 0,
	75, 33, 34, 76, 0, 0, 268, 37, 92, 35,
	0, 40, 0, 39, 91, 77, 80, 0, 75, 33,
	34, 76, 265, 0, 82, 37, 92, 35, 38, 0,
	0, 0, 0, 0, 0, 86, 0, 87, 36, 41,
	0, 0, 82, 0, 93, 95, 38, 0, 0, 81,
	90, 89, 88, 86, 0, 87, 36, 41, 0, 40,
	0, 39, 93, 95, 0, 0, 0, 81, 90, 89,
	88, 0, 0, 0, 0, 0, 0, 40, 0, 39,
	91, 77, 80, 0, 75, 33, 34, 76, 0, 0,
	261, 37, 92, 35, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 82, 0,
	0, 0, 38, 0, 0, 0, 0, 0, 0, 86,
	0, 87, 36, 41, 0, 0, 0, 0, 93, 95,
	0, 0, 0, 81, 90, 89, 88, 0, 0, 0,
	0, 0, 0, 40, 0, 39, 91, 77, 80, 0,
	75, 33, 34, 76, 0, 0, 249, 37, 92, 35,
	0, 0, 0, 0, 91, 77, 80, 0, 75, 33,
	34, 76, 0, 0, 82, 37, 92, 35, 38, 0,
	0, 0, 0, 0, 0, 86, 0, 87, 36, 41,
	0, 0, 82, 0, 93, 95, 38, 0, 0, 81,
	90, 89, 88, 86, 0, 87, 36, 41, 0, 40,
	0, 39, 93, 95, 0, 0, 0, 81, 90, 89,
	88, 0, 0, 0, 221, 0, 0, 40, 0, 39,
	91, 77, 80, 0, 75, 33, 34, 76, 0, 0,
	237, 37, 92, 35, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 82, 0,
	0, 0, 38, 0, 0, 0, 0, 0, 0, 86,
	0, 87, 36, 41, 0, 0, 0, 0, 93, 95,
	0, 0, 0, 81, 90, 89, 88, 0, 0, 0,
	0, 0, 0, 40, 0, 39, 91, 77, 80, 0,
	75, 33, 34, 76, 0, 0, 208, 37, 92, 35,
	0, 0, 0, 0, 91, 77, 80, 0, 75, 33,
	34, 76, 0, 0, 82, 37, 92, 35, 38, 0,
	192, 0, 0, 0, 0, 86, 0, 87, 36, 41,
	0, 0, 82, 0, 93, 95, 38, 0, 0, 81,
	90, 89, 88, 86, 0, 87, 36, 41, 0, 40,
	0, 39, 93, 95, 0, 0, 0, 81, 90, 89,
	88, 0, 0, 0, 0, 0, 0, 40, 0, 39,
	91, 77, 80, 0, 75, 33, 34, 76, 0, 0,
	99, 37, 92, 35, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 82, 0,
	0, 0, 38, 0, 0, 0, 0, 0, 0, 86,
	0, 87, 36, 41, 0, 0, 0, 0, 93, 95,
	0, 0, 0, 81, 90, 89, 88, 0, 0, 0,
	0, 0, 0, 40, 0, 39, 91, 77, 80, 0,
	75, 33, 34, 76, 0, 0, 58, 37, 92, 35,
	0, 0, 0, 0, 91, 77, 80, 0, 75, 33,
	34, 76, 0, 0, 82, 37, 92, 35, 38, 0,
	0, 0, 0, 0, 0, 86, 0, 87, 36, 41,
	0, 0, 82, 0, 93, 95, 38, 0, 0, 81,
	90, 89, 88, 86, 0, 87, 36, 41, 0, 40,
	0, 39, 93, 95, 0, 104, 105, 81, 90, 89,
	88, 37, 92, 35, 0, 0, 0, 40, 0, 39,
	0, 0, 0, 33, 34, 0, 0, 0, 102, 37,
	92, 35, 38, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 36, 41, 0, 0, 82, 0, 93, 95,
	38, 106, 107, 0, 0, 0, 0, 0, 0, 0,
	36, 41, 0, 40, 0, 39, 93, 95, 33, 34,
	0, 0, 0, 0, 37, 178, 35, 0, 0, 0,
	0, 40, 0, 39, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 38, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 36, 41, 0, 0, 0,
	0, 179, 95, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 40, 0, 39,
}

var yyPact = [...]int16{
	-3, -32768, -12, 27, 4, -32768, 223, -32768, -32768, -8,
	-32768, -32768, 221, -32768, 74, -32768, -32768, 216, 212, 242,
	-32768, -32768, 208, 141, 217, -32768, -32768, 112, 644, -32768,
	-32768, 204, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768,
	644, 644, 178, -32768, -32768, 578, -32768, 51, 25, -32768,
	1142, 204, -32768, -32768, 644, -32768, -32768, 1076, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, 1206, 1206, 1224, 7, 6,
	-32768, -32768, 1224, 55, -32768, 72, 1160, 22, 1224, 13,
	13, 203, 53, 104, 29, -32768, -32768, -32768, -32768, -32768,
	-32768, 171, 1206, 266, -32768, -32768, 1224, 1224, -32768, 44,
	-32768, 168, 154, -32768, -32768, 44, -32768, 1224, 1224, 22,
	22, 163, 92, 31, 44, 13, 194, 170, 1224, 1224,
	1224, 1224, 1224, -32768, 1010, 0, 55, 44, -28, 29,
	-32768, 55, 13, 29, -32768, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 992, 1206, 1206, 155, 92, 1224,
	1224, 1224, 1224, 1224, 1224, -32768, -32768, 860, 1224, -32768,
	-32768, 44, -32768, -32768, 55, 55, -32768, -32768, 10, -32768,
	-32768, -32768, 176, -32768, 29, 103, 73, -32768, -32768, -32768,
	-32768, -32768, 1206, 1224, -25, -32768, 1224, 31, 175, -4,
	135, -10, -10, -55, -55, -55, -32768, 926, -32768, 67,
	67, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 860, 3,
	-32768, 1206, -32768, -32768, 13, 13, 13, 150, -41, -32768,
	44, 842, -32768, 234, -32768, -32768, -32768, -32768, 3, 230,
	-32768, 1160, 147, -32768, 95, 84, 1160, 1269, 776, -32768,
	1160, 177, -32768, 1160, 1160, -32768, -32768, 710, 152, -32768,
	-32768, -32768, 1160, -32768, 1160, 692, 1269, 626, -32768, 233,
	-32768, 560, 494, -32768, -32768,
}

var yyPgo = [...]int16{
	0, 325, 324, 317, 313, 312, 311, 255, 262, 310,
	241, 158, 192, 306, 84, 54, 217, 27, 0, 5,
	332, 10, 304, 303, 301, 300, 299, 298, 286, 270,
	285, 284, 282, 281, 280, 279, 274, 21, 2, 12,
	4, 3, 1, 309, 271, 7, 8, 263, 302, 258,
	257, 96, 251, 6,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 3, 3, 3, 7, 4,
	4, 4, 8, 9, 9, 9, 5, 5, 5, 10,
	6, 6, 6, 12, 12, 13, 13, 13, 15, 16,
	16, 16, 16, 16, 17, 17, 17, 19, 14, 14,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 35, 36, 33, 31, 31,
	38, 38, 32, 32, 22, 22, 23, 23, 40, 40,
	40, 42, 42, 41, 41, 41, 37, 37, 37, 37,
	37, 37, 37, 37, 37, 37, 37, 37, 37, 43,
	43, 43, 24, 24, 44, 44, 45, 45, 45, 25,
	25, 26, 26, 47, 47, 46, 46, 46, 30, 30,
	30, 30, 30, 30, 39, 39, 18, 18, 18, 18,
	29, 29, 29, 48, 48, 48, 48, 48, 48, 48,
	20, 20, 20, 20, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 49, 49, 49, 51, 50, 50, 50,
	27, 28, 34, 34, 52, 52, 53, 53,
}

var yyR2 = [...]int8{
	0, 5, 0, 2, 2, 0, 1, 2, 2, 0,
	1, 2, 4, 0, 2, 1, 0, 1, 2, 4,
	0, 1, 2, 7, 6, 0, 3, 1, 1, 4,
	4, 4, 6, 6, 0, 3, 1, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 2, 2, 9, 8,
	1, 1, 11, 10, 5, 4, 7, 6, 0, 2,
	1, 4, 3, 0, 2, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 1, 1, 2, 2, 1,
	1, 1, 2, 1, 3, 1, 1, 1, 1, 3,
	3, 3, 3, 3, 1, 1, 1, 1, 3, 3,
	3, 3, 3, 2, 2, 1, 1, 4, 1, 1,
	3, 1, 1, 3, 3, 3, 3, 3, 3, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 3, 0, 1, 2, 3, 0, 1, 2,
	1, 1, 6, 5, 1, 2, 4, 3,
}

var yyChk = [...]int16{
	-32768, -1, -2, 50, -3, -7, 51, 16, 52, -4,
	-7, -8, 54, 15, -5, -8, -10, 49, 16, -6,
	-10, -12, 7, 16, -9, 16, -12, 16, 25, 14,
	16, 32, -11, 9, 10, 17, 46, 15, 36, 69,
	67, 47, -13, -15, 16, -49, -51, -11, -50, -11,
	33, 20, 68, -51, 42, 48, -11, -14, 14, -21,
	-22, -23, -24, -25, -26, -27, -28, -29, -30, -31,
	-32, -33, -34, -35, -36, 8, 11, 5, -39, -47,
	6, 57, 32, -16, -48, -18, 43, 45, 60, 59,
	58, 4, 16, 52, -20, 53, -11, -15, -11, 14,
	-21, -37, 32, -43, 9, 10, 55, 56, -11, -18,
	-29, -37, -44, -45, -11, -18, -29, 25, 63, 25,
	63, 20, -29, -48, -18, 32, 42, 42, 37, 38,
	39, 40, 41, 44, -14, -39, -16, -18, -43, -20,
	-48, -16, 32, -20, 16, 32, 47, 32, 21, 22,
	24, 23, 19, 66, 12, 34, 35, -37, -29, 27,
	26, 30, 28, 29, 31, -43, -43, 12, 20, -46,
	-11, -18, -29, -46, -16, -16, -39, -18, 16, 52,
	33, 33, -17, -19, -20, 16, 16, -46, -46, -46,
	-46, -46, 20, 25, -52, -53, 61, -48, -17, -20,
	-17, -20, -20, -20, -20, -20, -20, -14, 14, -37,
	-37, 33, -43, -43, -43, -43, -43, -43, -14, -40,
	-42, 64, -45, 33, 20, 32, 32, -37, -38, -11,
	-18, 62, -53, -43, 33, 48, 33, 14, -40, -41,
	-42, 13, -37, -19, -17, -17, 20, 65, -14, 14,
	12, -41, 14, -14, 12, 33, 33, -14, -38, -11,
	-18, 14, -14, 14, -14, 12, 20, -14, 14, -38,
	14, 12, -14, 14, 14,
}

var yyDef = [...]int16{
	2, -2, 5, 0, 9, 6, 0, 3, 4, 16,
	7, 10, 0, 8, 20, 11, 17, 0, 13, 1,
	18, 21, 0, 0, 0, 15, 22, 0, 0, 12,
	14, 25, 19, 134, 135, 136, 137, 138, 139, 140,
	143, 147, 0, 27, 28, 0, 144, 0, 0, 148,
	0, 0, 141, 145, 0, 142, 149, 0, 24, 39,
	40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
	50, 51, 52, 53, 54, 0, 0, 93, 104, 0,
	150, 151, 0, -2, -2, -2, 0, 0, 0, 0,
	0, 0, 116, 119, 0, 118, 131, 26, 146, 23,
	38, 0, 0, 0, -2, -2, 0, 0, -2, -2,
	91, 0, 92, 95, -2, -2, 98, 0, 0, 0,
	0, 0, 0, -2, 133, 34, 0, 0, 0, 0,
	0, 0, 0, 113, 0, 104, 57, 0, 0, 55,
	130, 132, 0, 56, 114, 34, 0, 34, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 91, 0,
	0, 0, 0, 0, 0, 87, 88, 68, 0, 99,
	-2, -2, 107, 100, 101, 102, 103, 115, 116, 119,
	120, 123, 0, 36, 37, 0, 0, 108, 109, 110,
	111, 112, 0, 0, 0, 154, 0, 130, 0, 0,
	0, 124, 125, 126, 127, 128, 129, 0, 65, 77,
	78, 76, 79, 80, 81, 82, 83, 84, 68, 73,
	70, 0, 94, 31, 0, 34, 34, 0, 0, -2,
	-2, 0, 155, 0, 29, 117, 30, 64, 73, 0,
	69, 75, 0, 35, 0, 0, 0, 0, 0, 153,
	157, 0, 67, 74, 72, 32, 33, 0, 0, 60,
	61, 152, 156, 66, 71, 0, 0, 0, 59, 0,
	58, 0, 0, 63, 62,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:95
		{
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:99
		{
			log_debug("[yacc]: package %v", yyDollar[2].s)
			l := yylex.(lexerwarpper).mf
			l.set_package(yyDollar[2].s)
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:106
		{
			log_debug("[yacc]: package %v", yyDollar[2].s)
			l := yylex.(lexerwarpper).mf
			l.set_package(yyDollar[2].s)
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:114
		{
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:124
		{
			log_debug("[yacc]: include %v", yyDollar[2].s)
			l := yylex.(lexerwarpper).mf
			l.add_include(yyDollar[2].s)
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:133
		{
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:143
		{
			log_debug("[yacc]: struct_define %v", yyDollar[2].s)
			l := yylex.(lexerwarpper).mf
			if (yyDollar[3].sn) != nil {
				p := (yyDollar[3].sn).(*struct_desc_memlist_node)
				l.add_struct_desc(yyDollar[2].s, p)
			}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:155
		{
			yyVAL.sn = nil
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:160
		{
			log_debug("[yacc]: struct_mem_declaration <- IDENTIFIER struct_mem_declaration")
			p := (yyDollar[1].sn).(*struct_desc_memlist_node)
			p.add_arg(yyDollar[2].s)
			yyVAL.sn = p
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:168
		{
			log_debug("[yacc]: struct_mem_declaration <- IDENTIFIER")
			p := &struct_desc_memlist_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_arg(yyDollar[1].s)
			yyVAL.sn = p
		}
	case 16:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:178
		{
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:188
		{
			log_debug("[yacc]: const_define %v", yyDollar[2].s)
			l := yylex.(lexerwarpper).mf
			l.add_const_desc(yyDollar[2].s, yyDollar[4].sn)
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:197
		{
		}
	case 23:
		yyDollar = yyS[yypt-7 : yypt+1]
//line yacc.y:209
		{
			log_debug("[yacc]: function_declaration <- block %v", yyDollar[2].s)
			p := &func_desc_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.funcname = yyDollar[2].s
			if yyDollar[4].sn != nil {
				p.arglist = yyDollar[4].sn.(*func_desc_arglist_node)
			}
			p.block = yyDollar[6].sn.(*block_node)
			l := yylex.(lexerwarpper).mf
			l.add_func_desc(p)
		}
	case 24:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yacc.y:222
		{
			log_debug("[yacc]: function_declaration <- empty %v", yyDollar[2].s)
			p := &func_desc_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.funcname = yyDollar[2].s
			if yyDollar[4].sn != nil {
				p.arglist = yyDollar[4].sn.(*func_desc_arglist_node)
			}
			p.block = nil
			l := yylex.(lexerwarpper).mf
			l.add_func_desc(p)
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:237
		{
			yyVAL.sn = nil
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:242
		{
			log_debug("[yacc]: function_declaration_arguments <- arg function_declaration_arguments")
			p := (yyDollar[1].sn).(*func_desc_arglist_node)
			p.add_arg(yyDollar[3].s)
			yyVAL.sn = p
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:250
		{
			log_debug("[yacc]: function_declaration_arguments <- arg")
			p := &func_desc_arglist_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_arg(yyDollar[1].s)
			yyVAL.sn = p
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:260
		{
			log_debug("[yacc]: arg <- IDENTIFIER %v", yyDollar[1].s)
			p := &identifier_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			yyVAL.sn = p
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:270
		{
			log_debug("[yacc]: function_call <- function_call_arguments %v", yyDollar[1].s)
			p := &function_call_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.fuc = yyDollar[1].s
			p.prefunc = nil
			if yyDollar[3].sn != nil {
				p.arglist = (yyDollar[3].sn).(*function_call_arglist_node)
			}
			p.fakecall = false
			p.classmem_call = false
			yyVAL.sn = p
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:284
		{
			log_debug("[yacc]: function_call <- function_call_arguments %v", yyDollar[1].s)
			p := &function_call_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.fuc = yyDollar[1].s
			p.prefunc = nil
			if yyDollar[3].sn != nil {
				p.arglist = (yyDollar[3].sn).(*function_call_arglist_node)
			}
			p.fakecall = false
			p.classmem_call = false
			yyVAL.sn = p
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:298
		{
			log_debug("[yacc]: function_call <- function_call_arguments")
			p := &function_call_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.fuc = ""
			p.prefunc = yyDollar[1].sn
			if yyDollar[3].sn != nil {
				p.arglist = (yyDollar[3].sn).(*function_call_arglist_node)
			}
			p.fakecall = false
			p.classmem_call = false
			yyVAL.sn = p
		}
	case 32:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yacc.y:312
		{
			log_debug("[yacc]: function_call <- mem function_call_arguments %v", yyDollar[3].s)
			p := &function_call_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.fuc = yyDollar[3].s
			p.prefunc = nil
			if yyDollar[5].sn == nil {
				p.arglist = &function_call_arglist_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			} else {
				p.arglist = (yyDollar[5].sn).(*function_call_arglist_node)
			}
			p.arglist.add_arg(yyDollar[1].sn)
			p.fakecall = false
			p.classmem_call = true
			yyVAL.sn = p
		}
	case 33:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yacc.y:329
		{
			log_debug("[yacc]: function_call <- mem function_call_arguments %v", yyDollar[3].s)
			p := &function_call_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.fuc = yyDollar[3].s
			p.prefunc = nil
			if yyDollar[5].sn == nil {
				p.arglist = &function_call_arglist_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			} else {
				p.arglist = (yyDollar[5].sn).(*function_call_arglist_node)
			}
			p.arglist.add_arg(yyDollar[1].sn)
			p.fakecall = false
			p.classmem_call = true
			yyVAL.sn = p
		}
	case 34:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:348
		{
			yyVAL.sn = nil
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:353
		{
			log_debug("[yacc]: function_call_arguments <- arg_expr function_call_arguments")
			p := (yyDollar[1].sn).(*function_call_arglist_node)
			p.add_arg(yyDollar[3].sn)
			yyVAL.sn = p
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:361
		{
			log_debug("[yacc]: function_call_arguments <- arg_expr")
			p := &function_call_arglist_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_arg(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:371
		{
			log_debug("[yacc]: arg_expr <- expr_value")
			yyVAL.sn = yyDollar[1].sn
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:381
		{
			log_debug("[yacc]: block <- block stmt")
			p := (yyDollar[1].sn).(*block_node)
			p.add_stmt(yyDollar[2].sn)
			yyVAL.sn = p
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:389
		{
			log_debug("[yacc]: block <- stmt")
			p := &block_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_stmt(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:399
		{
			log_debug("[yacc]: stmt <- while_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:405
		{
			log_debug("[yacc]: stmt <- if_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:411
		{
			log_debug("[yacc]: stmt <- return_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:417
		{
			log_debug("[yacc]: stmt <- assign_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:423
		{
			log_debug("[yacc]: stmt <- multi_assign_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:429
		{
			log_debug("[yacc]: stmt <- break")
			yyVAL.sn = yyDollar[1].sn
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:435
		{
			log_debug("[yacc]: stmt <- continue")
			yyVAL.sn = yyDollar[1].sn
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:441
		{
			log_debug("[yacc]: stmt <- expr")
			yyVAL.sn = yyDollar[1].sn
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:447
		{
			log_debug("[yacc]: stmt <- math_assign_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:453
		{
			log_debug("[yacc]: stmt <- for_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:459
		{
			log_debug("[yacc]: stmt <- for_loop_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:465
		{
			log_debug("[yacc]: stmt <- fake_call_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:471
		{
			log_debug("[yacc]: stmt <- switch_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:477
		{
			log_debug("[yacc]: stmt <- sleep_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:483
		{
			log_debug("[yacc]: stmt <- yield_stmt")
			yyVAL.sn = yyDollar[1].sn
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:491
		{
			log_debug("[yacc]: sleep_stmt <- SLEEP expr_value")
			p := &sleep_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.time = yyDollar[2].sn
			yyVAL.sn = p
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:501
		{
			log_debug("[yacc]: yield_stmt <- YIELD expr_value")
			p := &yield_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.time = yyDollar[2].sn
			yyVAL.sn = p
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:511
		{
			log_debug("[yacc]: fake_call_stmt <- fake function_call")
			p := (yyDollar[2].sn).(*function_call_node)
			p.fakecall = true
			yyVAL.sn = p
		}
	case 58:
		yyDollar = yyS[yypt-9 : yypt+1]
//line yacc.y:521
		{
			log_debug("[yacc]: for_stmt <- block cmp block")
			p := &for_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[4].sn).(*cmp_stmt)
			p.beginblock = (yyDollar[2].sn).(*block_node)
			p.endblock = (yyDollar[6].sn).(*block_node)
			p.block = (yyDollar[8].sn).(*block_node)
			yyVAL.sn = p
		}
	case 59:
		yyDollar = yyS[yypt-8 : yypt+1]
//line yacc.y:532
		{
			log_debug("[yacc]: for_stmt <- block cmp")
			p := &for_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[4].sn).(*cmp_stmt)
			p.beginblock = (yyDollar[2].sn).(*block_node)
			p.endblock = (yyDollar[6].sn).(*block_node)
			p.block = nil
			yyVAL.sn = p
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:545
		{
			log_debug("[yacc]: for_loop_value <- explicit_value")
			yyVAL.sn = yyDollar[1].sn
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:551
		{
			log_debug("[yacc]: for_loop_value <- variable")
			yyVAL.sn = yyDollar[1].sn
		}
	case 62:
		yyDollar = yyS[yypt-11 : yypt+1]
//line yacc.y:559
		{
			log_debug("[yacc]: for_loop_stmt <- block")
			p := &for_loop_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}

			p.iter = yyDollar[2].sn
			p.begin = yyDollar[4].sn
			p.end = yyDollar[6].sn
			p.step = yyDollar[8].sn
			p.block = yyDollar[10].sn.(*block_node)

			yyVAL.sn = p
		}
	case 63:
		yyDollar = yyS[yypt-10 : yypt+1]
//line yacc.y:573
		{
			log_debug("[yacc]: for_loop_stmt <- block")
			p := &for_loop_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}

			p.iter = yyDollar[2].sn
			p.begin = yyDollar[4].sn
			p.end = yyDollar[6].sn
			p.step = yyDollar[8].sn
			p.block = nil

			yyVAL.sn = p
		}
	case 64:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yacc.y:589
		{
			log_debug("[yacc]: while_stmt <- cmp block")
			p := &while_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[2].sn).(*cmp_stmt)
			p.block = (yyDollar[4].sn).(*block_node)
			yyVAL.sn = p
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:598
		{
			log_debug("[yacc]: while_stmt <- cmp")
			p := &while_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[2].sn).(*cmp_stmt)
			p.block = nil
			yyVAL.sn = p
		}
	case 66:
		yyDollar = yyS[yypt-7 : yypt+1]
//line yacc.y:609
		{
			log_debug("[yacc]: if_stmt <- cmp block")
			p := &if_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[2].sn).(*cmp_stmt)
			p.block = (yyDollar[4].sn).(*block_node)
			if yyDollar[5].sn != nil {
				p.elseifs = (yyDollar[5].sn).(*elseif_stmt_list)
			}
			if yyDollar[6].sn != nil {
				p.elses = (yyDollar[6].sn).(*else_stmt)
			}
			yyVAL.sn = p
		}
	case 67:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yacc.y:624
		{
			log_debug("[yacc]: if_stmt <- cmp")
			p := &if_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[2].sn).(*cmp_stmt)
			p.block = nil
			if yyDollar[4].sn != nil {
				p.elseifs = (yyDollar[4].sn).(*elseif_stmt_list)
			}
			if yyDollar[5].sn != nil {
				p.elses = (yyDollar[5].sn).(*else_stmt)
			}
			yyVAL.sn = p
		}
	case 68:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:641
		{
			yyVAL.sn = nil
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:646
		{
			log_debug("[yacc]: elseif_stmt_list <- elseif_stmt_list elseif_stmt")
			p := (yyDollar[1].sn).(*elseif_stmt_list)
			p.add_stmt(yyDollar[2].sn)
			yyVAL.sn = p
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:654
		{
			log_debug("[yacc]: elseif_stmt_list <- elseif_stmt")
			p := &elseif_stmt_list{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_stmt(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 71:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:664
		{
			log_debug("[yacc]: elseif_stmt <- ELSEIF cmp THEN block")
			p := &elseif_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[2].sn).(*cmp_stmt)
			p.block = (yyDollar[4].sn).(*block_node)
			yyVAL.sn = p
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:673
		{
			log_debug("[yacc]: elseif_stmt <- ELSEIF cmp THEN block")
			p := &elseif_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = (yyDollar[2].sn).(*cmp_stmt)
			p.block = nil
			yyVAL.sn = p
		}
	case 73:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:684
		{
			yyVAL.sn = nil
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:689
		{
			log_debug("[yacc]: else_stmt <- block")
			p := &else_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.block = (yyDollar[2].sn).(*block_node)
			yyVAL.sn = p
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:697
		{
			log_debug("[yacc]: else_stmt <- empty")
			p := &else_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.block = nil
			yyVAL.sn = p
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:707
		{
			log_debug("[yacc]: cmp <- ( cmp )")
			yyVAL.sn = yyDollar[2].sn
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:713
		{
			log_debug("[yacc]: cmp <- cmp AND cmp")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "&&"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:723
		{
			log_debug("[yacc]: cmp <- cmp OR cmp")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "||"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:733
		{
			log_debug("[yacc]: cmp <- cmp_value LESS cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "<"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:743
		{
			log_debug("[yacc]: cmp <- cmp_value MORE cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = ">"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:753
		{
			log_debug("[yacc]: cmp <- cmp_value EQUAL cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "=="
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:763
		{
			log_debug("[yacc]: cmp <- cmp_value MORE_OR_EQUAL cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = ">="
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:773
		{
			log_debug("[yacc]: cmp <- cmp_value LESS_OR_EQUAL cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "<="
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:783
		{
			log_debug("[yacc]: cmp <- cmp_value NOT_EQUAL cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "!="
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:793
		{
			log_debug("[yacc]: cmp <- true")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "true"
			p.left = nil
			p.right = nil
			yyVAL.sn = p
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:803
		{
			log_debug("[yacc]: cmp <- false")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "false"
			p.left = nil
			p.right = nil
			yyVAL.sn = p
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:813
		{
			log_debug("[yacc]: cmp <- cmp_value IS cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "is"
			p.left = yyDollar[2].sn
			p.right = nil
			yyVAL.sn = p
		}
	case 88:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:823
		{
			log_debug("[yacc]: cmp <- cmp_value NOT cmp_value")
			p := &cmp_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = "not"
			p.left = yyDollar[2].sn
			p.right = nil
			yyVAL.sn = p
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:835
		{
			log_debug("[yacc]: cmp_value <- explicit_value")
			yyVAL.sn = yyDollar[1].sn
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:841
		{
			log_debug("[yacc]: cmp_value <- variable")
			yyVAL.sn = yyDollar[1].sn
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:847
		{
			log_debug("[yacc]: cmp_value <- expr")
			yyVAL.sn = yyDollar[1].sn
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:855
		{
			log_debug("[yacc]: return_stmt <- RETURN return_value_list")
			p := &return_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.returnlist = (yyDollar[2].sn).(*return_value_list_node)
			yyVAL.sn = p
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:863
		{
			log_debug("[yacc]: return_stmt <- RETURN")
			p := &return_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.returnlist = nil
			yyVAL.sn = p
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:873
		{
			log_debug("[yacc]: return_value_list <- return_value_list return_value")
			p := (yyDollar[1].sn).(*return_value_list_node)
			p.add_arg(yyDollar[3].sn)
			yyVAL.sn = p
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:881
		{
			log_debug("[yacc]: return_value_list <- return_value")
			p := &return_value_list_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_arg(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:891
		{
			log_debug("[yacc]: return_value <- explicit_value")
			yyVAL.sn = yyDollar[1].sn
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:897
		{
			log_debug("[yacc]: return_value <- variable")
			yyVAL.sn = yyDollar[1].sn
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:903
		{
			log_debug("[yacc]: return_value <- expr")
			yyVAL.sn = yyDollar[1].sn
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:911
		{
			log_debug("[yacc]: assign_stmt <- var assign_value")
			p := &assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.value = yyDollar[3].sn
			p.isnew = false
			yyVAL.sn = p
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:921
		{
			log_debug("[yacc]: new assign_stmt <- var assign_value")
			p := &assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.value = yyDollar[3].sn
			p.isnew = true
			yyVAL.sn = p
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:933
		{
			log_debug("[yacc]: multi_assign_stmt <- var_list function_call")
			p := &multi_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.varlist = (yyDollar[1].sn).(*var_list_node)
			p.value = yyDollar[3].sn
			p.isnew = false
			yyVAL.sn = p
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:943
		{
			log_debug("[yacc]: new multi_assign_stmt <- var_list function_call")
			p := &multi_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.varlist = (yyDollar[1].sn).(*var_list_node)
			p.value = yyDollar[3].sn
			p.isnew = true
			yyVAL.sn = p
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:955
		{
			log_debug("[yacc]: var_list <- var_list var")
			p := (yyDollar[1].sn).(*var_list_node)
			p.add_arg(yyDollar[3].sn)
			yyVAL.sn = p
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:963
		{
			log_debug("[yacc]: var_list <- var")
			p := &var_list_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_arg(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:973
		{
			log_debug("[yacc]: assign_value <- explicit_value")
			yyVAL.sn = yyDollar[1].sn
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:979
		{
			log_debug("[yacc]: assign_value <- variable")
			yyVAL.sn = yyDollar[1].sn
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:985
		{
			log_debug("[yacc]: assign_value <- expr")
			yyVAL.sn = yyDollar[1].sn
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:993
		{
			log_debug("[yacc]: math_assign_stmt <- variable assign_value")
			p := &math_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.oper = "+="
			p.value = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1003
		{
			log_debug("[yacc]: math_assign_stmt <- variable assign_value")
			p := &math_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.oper = "-="
			p.value = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1013
		{
			log_debug("[yacc]: math_assign_stmt <- variable assign_value")
			p := &math_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.oper = "/="
			p.value = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1023
		{
			log_debug("[yacc]: math_assign_stmt <- variable assign_value")
			p := &math_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.oper = "*="
			p.value = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1033
		{
			log_debug("[yacc]: math_assign_stmt <- variable assign_value")
			p := &math_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.oper = "%="
			p.value = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 113:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:1043
		{
			log_debug("[yacc]: math_assign_stmt <- variable INC")
			pp := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			pp.str = "1"
			pp.ty = EVT_NUM

			p := &math_assign_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.vr = yyDollar[1].sn
			p.oper = "+="
			p.value = pp
			yyVAL.sn = p
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:1059
		{
			log_debug("[yacc]: var <- VAR_BEGIN IDENTIFIER %v", yyDollar[2].s)
			p := &var_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[2].s
			yyVAL.sn = p
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1067
		{
			log_debug("[yacc]: var <- variable")
			yyVAL.sn = yyDollar[1].sn
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1075
		{
			log_debug("[yacc]: variable <- IDENTIFIER %v", yyDollar[1].s)
			p := &variable_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			yyVAL.sn = p
		}
	case 117:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:1083
		{
			log_debug("[yacc]: container_get_node <- IDENTIFIER[expr_value] %v", yyDollar[1].s)
			p := &container_get_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.container = yyDollar[1].s
			p.key = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1092
		{
			log_debug("[yacc]: variable <- IDENTIFIER_POINTER %v", yyDollar[1].s)
			p := &struct_pointer_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			yyVAL.sn = p
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1100
		{
			log_debug("[yacc]: variable <- IDENTIFIER_DOT %v", yyDollar[1].s)
			p := &variable_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			yyVAL.sn = p
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1110
		{
			log_debug("[yacc]: expr <- (expr)")
			yyVAL.sn = yyDollar[2].sn
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1116
		{
			log_debug("[yacc]: expr <- function_call")
			yyVAL.sn = yyDollar[1].sn
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1122
		{
			log_debug("[yacc]: expr <- math_expr")
			yyVAL.sn = yyDollar[1].sn
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1130
		{
			log_debug("[yacc]: math_expr <- (math_expr)")
			yyVAL.sn = yyDollar[2].sn
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1136
		{
			log_debug("[yacc]: math_expr <- expr_value %v expr_value", yyDollar[2].s)
			p := &math_expr_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.oper = "+"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1146
		{
			log_debug("[yacc]: math_expr <- expr_value %v expr_value", yyDollar[2].s)
			p := &math_expr_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.oper = "-"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1156
		{
			log_debug("[yacc]: math_expr <- expr_value %v expr_value", yyDollar[2].s)
			p := &math_expr_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.oper = "*"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1166
		{
			log_debug("[yacc]: math_expr <- expr_value %v expr_value", yyDollar[2].s)
			p := &math_expr_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.oper = "/"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 128:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1176
		{
			log_debug("[yacc]: math_expr <- expr_value %v expr_value", yyDollar[2].s)
			p := &math_expr_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.oper = "%"
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1186
		{
			log_debug("[yacc]: math_expr <- expr_value %v expr_value", yyDollar[2].s)
			p := &math_expr_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.oper = ".."
			p.left = yyDollar[1].sn
			p.right = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1198
		{
			log_debug("[yacc]: expr_value <- math_expr")
			yyVAL.sn = yyDollar[1].sn
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1204
		{
			log_debug("[yacc]: expr_value <- explicit_value")
			yyVAL.sn = yyDollar[1].sn
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1210
		{
			log_debug("[yacc]: expr_value <- function_call")
			yyVAL.sn = yyDollar[1].sn
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1216
		{
			log_debug("[yacc]: expr_value <- variable")
			yyVAL.sn = yyDollar[1].sn
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1224
		{
			log_debug("[yacc]: explicit_value <- FTRUE")
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			p.ty = EVT_TRUE
			yyVAL.sn = p
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1233
		{
			log_debug("[yacc]: explicit_value <- FFALSE")
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			p.ty = EVT_FALSE
			yyVAL.sn = p
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1242
		{
			log_debug("[yacc]: explicit_value <- NUMBER %v", yyDollar[1].s)
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			p.ty = EVT_NUM
			yyVAL.sn = p
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1251
		{
			log_debug("[yacc]: explicit_value <- FKUUID %v", yyDollar[1].s)
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			p.ty = EVT_UUID
			yyVAL.sn = p
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1260
		{
			log_debug("[yacc]: explicit_value <- STRING_DEFINITION %v", yyDollar[1].s)
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			p.ty = EVT_STR
			yyVAL.sn = p
		}
	case 139:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1269
		{
			log_debug("[yacc]: explicit_value <- FKFLOAT %v", yyDollar[1].s)
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			p.ty = EVT_FLOAT
			yyVAL.sn = p
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1278
		{
			log_debug("[yacc]: explicit_value <- FNULL %v", yyDollar[1].s)
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = yyDollar[1].s
			p.ty = EVT_NULL
			yyVAL.sn = p
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1287
		{
			log_debug("[yacc]: explicit_value <- const_map_list_value")
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = ""
			p.ty = EVT_MAP
			p.v = yyDollar[2].sn
			yyVAL.sn = p
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1297
		{
			log_debug("[yacc]: explicit_value <- const_array_list_value")
			p := &explicit_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.str = ""
			p.ty = EVT_ARRAY
			p.v = yyDollar[2].sn
			yyVAL.sn = p
		}
	case 143:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:1309
		{
			log_debug("[yacc]: const_map_list_value <- null")
			p := &const_map_list_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			yyVAL.sn = p
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1316
		{
			log_debug("[yacc]: const_map_list_value <- const_map_value")
			p := &const_map_list_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_ele(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 145:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:1324
		{
			log_debug("[yacc]: const_map_list_value <- const_map_list_value const_map_value")
			p := (yyDollar[1].sn).(*const_map_list_value_node)
			p.add_ele(yyDollar[2].sn)
			yyVAL.sn = p
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1334
		{
			log_debug("[yacc]: const_map_value <- explicit_value")
			p := &const_map_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.k = yyDollar[1].sn
			p.v = yyDollar[3].sn
			yyVAL.sn = p
		}
	case 147:
		yyDollar = yyS[yypt-0 : yypt+1]
//line yacc.y:1345
		{
			log_debug("[yacc]: const_array_list_value <- null")
			p := &const_array_list_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			yyVAL.sn = p
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1352
		{
			log_debug("[yacc]: const_array_list_value <- explicit_value")
			p := &const_array_list_value_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_ele(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:1360
		{
			log_debug("[yacc]: const_array_list_value <- const_array_list_value explicit_value")
			p := (yyDollar[1].sn).(*const_array_list_value_node)
			p.add_ele(yyDollar[2].sn)
			yyVAL.sn = p
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1370
		{
			log_debug("[yacc]: break <- BREAK")
			p := &break_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			yyVAL.sn = p
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1379
		{
			log_debug("[yacc]: CONTINUE")
			p := &continue_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			yyVAL.sn = p
		}
	case 152:
		yyDollar = yyS[yypt-6 : yypt+1]
//line yacc.y:1388
		{
			log_debug("[yacc]: switch_stmt")
			p := &switch_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = yyDollar[2].sn
			p.caselist = yyDollar[3].sn
			p.def = yyDollar[5].sn
			yyVAL.sn = p
		}
	case 153:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yacc.y:1398
		{
			log_debug("[yacc]: switch_stmt")
			p := &switch_stmt{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = yyDollar[2].sn
			p.caselist = yyDollar[3].sn
			p.def = nil
			yyVAL.sn = p
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:1410
		{
			log_debug("[yacc]: switch_case_list <- switch_case_define")
			p := &switch_caselist_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.add_case(yyDollar[1].sn)
			yyVAL.sn = p
		}
	case 155:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:1418
		{
			log_debug("[yacc]: switch_case_list <- switch_case_list switch_case_define")
			p := (yyDollar[1].sn).(*switch_caselist_node)
			p.add_case(yyDollar[2].sn)
			yyVAL.sn = p
		}
	case 156:
		yyDollar = yyS[yypt-4 : yypt+1]
//line yacc.y:1428
		{
			log_debug("[yacc]: switch_case_define")
			p := &switch_case_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = yyDollar[2].sn
			p.block = yyDollar[4].sn
			yyVAL.sn = p
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:1437
		{
			log_debug("[yacc]: switch_case_define")
			p := &switch_case_node{syntree_node_base: syntree_node_base{yylex.(lexerwarpper).yyLexer.(*Lexer).Line()}}
			p.cmp = yyDollar[2].sn
			p.block = nil
			yyVAL.sn = p
		}
	}
	goto yystack /* stack new state and value */
}
